---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test
spec:
  selector:
    matchLabels:
      app: web
  revisionHistoryLimit: 7
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app
          image: sirfragalot/docker-demo:dcus
          ports:
            - containerPort: 8080


